local query = require "editor-script-atlas.query"
local dialogs = require "editor-script-atlas.dialogs"
local utils = require "editor-script-atlas.utils"

local M = {}


local function add_images_as_animation(opts)
    local animation_name = editor.ui.show_dialog(dialogs.name_dialog({ title = "Add images as animation" }))
    if animation_name == nil then
        return
    end
    local atlas = utils.get_atlas(opts)
    for _, id in pairs(opts.selection) do
        local path = editor.get(id, "path")
        if not utils.ends_with(path, ".atlas") then
            editor.tx.add(atlas, "animations", {
                id=animation_name,
                image=path
            })
        end
    end
end


local function add_images_as_images(opts)
    local atlas = utils.get_atlas(opts)
    local txs = {}
    for _, id in pairs(opts.selection) do
        local path = editor.get(id, "path")
        if not utils.ends_with(path, ".atlas") then
            table.insert(txs, editor.tx.add(atlas, "images", {image=path}))
        end
    end
    editor.transact(txs)
end


local function add_all_in_directory(atlas, directory, txs, recursive)
    local children = editor.get(directory, "children")
    for i = 1, #children do
        local resource_path = editor.get(children[i], "path")
        if utils.ends_with(resource_path, ".png") then
            table.insert(txs, editor.tx.add(atlas, "images", {image=resource_path}))
        end
        if recursive and editor.resource_attributes(resource_path).is_directory then
            add_all_in_directory(atlas, resource_path, txs, recursive)
        end
    end
end

local function add_folders_as_animations(atlas, directory, txs)
    local children = editor.get(directory, "children")
    for i = 1, #children do
        local resource_path = editor.get(children[i], "path")
        if utils.ends_with(resource_path, ".png") then
            table.insert(txs, editor.tx.add(atlas, "images", {image=resource_path}))
        end
        if editor.resource_attributes(resource_path).is_directory then
            local _, name, _ = utils.path_segments(resource_path)
            local grandchildren = editor.get(resource_path, "children")
            local images = {}
            for j = 1, #grandchildren do
                local grandchild_path = editor.get(grandchildren[j], "path")
                if utils.ends_with(grandchild_path, ".png") then
                    table.insert(images, {image=grandchild_path})
                end
            end
            if #images then
                table.insert(txs, editor.tx.add(atlas, "animations", {id = name, images=images}))
            end
        end
    end
end
    
local function create_atlas_from_folder(opts)
    local atlas = opts.selection .. ".atlas"
    
    local txs = {}

    -- If the atlas already exists we ask if we should continue
    if editor.resource_attributes(atlas).exists then
        local atlas_name = editor.ui.show_dialog(dialogs.yes_no_dialog({ title = "Resource exists", text = "Recreate the atlas?" }))
        if atlas_name == false then
            return
        end
        table.insert(txs, editor.tx.clear(atlas, "images"))
        table.insert(txs, editor.tx.clear(atlas, "animations"))
    else
        -- No atlas exists, create a new empty file.
        local atlas_file = io.open("." .. atlas, "w")
        if atlas_file == nil then
            return
        end
        atlas_file:write('')
        atlas_file:close()
    end

    
    if query.directory_contains_image_subdirectories(opts) then
        local creation_mode = editor.ui.show_dialog(dialogs.sub_directories_dialog({ title = "Subdirectories found.", text = "How do you want to create the atlas?" }))
        if creation_mode == 1 then
            add_all_in_directory(atlas, opts.selection, txs, false)
        elseif creation_mode == 2 then
            add_folders_as_animations(atlas, opts.selection, txs)
        elseif creation_mode == 3 then
            add_all_in_directory(atlas, opts.selection, txs, true)
        end
    else
        add_all_in_directory(atlas, opts.selection, txs)
    end

    editor.transact(txs)
end


local function add_images_to_new_atlas(opts)
    local atlas_name = editor.ui.show_dialog(dialogs.name_dialog({ title = "Create a new atlas" }))
    if atlas_name == nil then
        return
    end


    local base_path = utils.path_segments(editor.get(opts.selection[1], "path"))
    local atlas = base_path .. atlas_name .. ".atlas"

    local atlas_file = io.open("." .. atlas, "w")
    if atlas_file == nil then
        return
    end
    
    atlas_file:write('')
    atlas_file:close()
    
    local txs = {}
    for _, id in pairs(opts.selection) do
        local path = editor.get(id, "path")
        table.insert(txs, editor.tx.add(atlas, "images", {image=path}))
    end

    editor.transact(txs)
end


function M.get_commands()
    return {
        {
            label="Add images...",
            locations = {"Assets"},
            query = {
                selection = {type = "resource", cardinality = "many"}
            },
            active = query.images_and_atlas_are_selected,
            run = add_images_as_images
        },
        {
            label="Add images as animation...",
            locations = {"Assets"},
            query = {
                selection = {type = "resource", cardinality = "many"}
            },
            active = query.images_and_atlas_are_selected,
            run = add_images_as_animation
        },
        {
            label="Create New Atlas",
            locations = {"Assets"},
            query = {
                selection = {type = "resource", cardinality = "many"}
            },
            active = query.images_but_no_atlas_are_selected,
            run = add_images_to_new_atlas
        },
        {
            label="Create New Atlas",
            locations = {"Assets"},
            query = {
                selection = {type = "resource", cardinality = "one"}
            },
            active = query.directory_with_images_selected,
            run = create_atlas_from_folder
        }
    }
end

return M
